### ISSUE TITLE
import threeML fails

### ISSUE THREAD

**Issue by josephsaji** [threeML/threeML#449]
Even after a successful installation of threeML, `from threeML import *` end up in an error.  error is given as 
ModuleNotFoundError: ' no module named naima' 
AttributeError : ''config object has no attribute logging"

installation was done using miniconda. have tried ti install nyma package manually, but still the error persist.

**Comment by henrikef** [comment]
Hi @josephsaji , could you please post the entire output you get after you tried to import threeML?

Also, could you please post the output of the following bash commands: `conda list | grep threeml` and `conda list | grep astromodels` and `python --version`.

**Comment by josephsaji** [comment]
hi,
thanks for the quick reply.
I have attached the screenshots of this version check as well as error
along with this mail. pls mail me if anything more is required.

**Comment by henrikef** [comment]
I see. This should be fixed in the next tag. In the mean time, please try updating to the latest versions of threeML/astromodels from github:

```
pip install --upgrade git+https://github.com/threeml/astromodels.git
pip install --upgrade git+https://github.com/threeml/threeML.git
```

(Btw, the real problem is not that naima is missing (which should only lead to a warning), but rather that it runs into an error when it tries to report that naima is not available. We recently updated the way error messages are logged, and it seems the new functionality is not fully consistent in the last tags of threeML/astromodels.)

**Comment by asattools** [comment]
Hi, 
I was getting the same problem for a long time and tried a lot to fix it. After the naima installation, we still get a problem for pygsl. While trying to install pygsl, I am not able to install it in python 3.7 which is installed with threeML from conda-forge

Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:59:12) 
[Clang 11.0.1 ] on darwin

However, the installation of pygsl is successful in the python 3.8 which is anaconda3/python 

Python 3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygsl
>>> 

The problem seems to me with Clang 11.0.1 which is coming with threeML python 3.7 as pygsl is successfully installed in default anaconda3 python 3.8.


Please let me know how to fix this.


Regards,
Vikas

**Comment by asattools** [comment]
Hi,

It is working now after the installation with updated install_threeML.sh file.



Thanks a lot.
